<?php
defined( 'ABSPATH' ) || exit;

/**
 * The form schema contract.
 *
 * A schema is intentionally flat and declarative so it can be (a) produced by
 * the CF7 importer, (b) generated by an LLM later, and (c) round-tripped through
 * the React builder without loss. This class is the single source of truth for
 * the allowed field types, operators and the normalize/sanitize pass that every
 * inbound schema must go through before it touches the database.
 *
 * Shape:
 * {
 *   "version": 1,
 *   "steps": [
 *     { "id": "step_1", "title": "...", "description": "...",
 *       "fields": [ <field>, ... ] }
 *   ]
 * }
 *
 * <field>:
 * {
 *   "id": "fld_x", "type": "text", "name": "parent_name", "label": "...",
 *   "placeholder": "", "help": "", "required": true,
 *   "options": [ {"label":"","value":""} ],   // choice fields
 *   "content": "<p>..</p>",                    // html block
 *   "config": { ... },                         // type-specific
 *   "conditional": { "enabled":false, "action":"show", "match":"all",
 *                    "rules":[ {"field":"name","op":"is","value":"v"} ] }
 * }
 */
class OFB_Schema {

	const VERSION = 1;

	/** Field types that collect a value from the visitor. */
	const INPUT_TYPES = [ 'text', 'email', 'tel', 'number', 'date', 'time', 'textarea', 'select', 'radio', 'checkbox', 'dropdown', 'session_picker' ];

	/** Field types that render content but collect nothing. */
	const STATIC_TYPES = [ 'html' ];

	/** Field types whose value is a list of choices. */
	const CHOICE_TYPES = [ 'select', 'radio', 'checkbox', 'dropdown' ];

	/** Conditional operators understood by both PHP and JS evaluators. */
	const OPERATORS = [ 'is', 'is_not', 'contains', 'not_contains', 'gt', 'lt', 'gte', 'lte', 'empty', 'not_empty' ];

	public static function all_types(): array {
		return array_merge( self::INPUT_TYPES, self::STATIC_TYPES );
	}

	public static function is_input_type( string $type ): bool {
		return in_array( $type, self::INPUT_TYPES, true );
	}

	/** A fresh, valid, empty schema. */
	public static function blank(): array {
		return [
			'version' => self::VERSION,
			'steps'   => [
				[ 'id' => 'step_1', 'title' => __( 'Step 1', 'open-form-builder' ), 'description' => '', 'fields' => [] ],
			],
		];
	}

	/**
	 * Normalize + sanitize a raw schema from the editor or importer. Unknown keys
	 * are dropped; unknown field types are dropped; everything is type-coerced.
	 * The result is always safe to JSON-encode and store.
	 */
	public static function normalize( $raw ): array {
		if ( ! is_array( $raw ) ) {
			return self::blank();
		}

		$steps     = [];
		$raw_steps = isset( $raw['steps'] ) && is_array( $raw['steps'] ) ? $raw['steps'] : [];

		foreach ( $raw_steps as $i => $step ) {
			if ( ! is_array( $step ) ) {
				continue;
			}
			$fields = [];
			$raw_fields = isset( $step['fields'] ) && is_array( $step['fields'] ) ? $step['fields'] : [];
			foreach ( $raw_fields as $field ) {
				$clean = self::normalize_field( $field );
				if ( null !== $clean ) {
					$fields[] = $clean;
				}
			}
			$steps[] = [
				'id'          => self::clean_id( $step['id'] ?? '', 'step_' . ( $i + 1 ) ),
				'title'       => sanitize_text_field( (string) ( $step['title'] ?? '' ) ),
				'description' => sanitize_textarea_field( (string) ( $step['description'] ?? '' ) ),
				'fields'      => $fields,
			];
		}

		if ( empty( $steps ) ) {
			return self::blank();
		}

		return [ 'version' => self::VERSION, 'steps' => $steps ];
	}

	/** @return array|null Clean field, or null if it should be dropped. */
	private static function normalize_field( $field ): ?array {
		if ( ! is_array( $field ) ) {
			return null;
		}
		$type = sanitize_key( (string) ( $field['type'] ?? '' ) );
		if ( ! in_array( $type, self::all_types(), true ) ) {
			return null;
		}

		$out = [
			'id'          => self::clean_id( $field['id'] ?? '', 'fld_' . wp_generate_password( 8, false, false ) ),
			'type'        => $type,
			'name'        => self::clean_name( $field['name'] ?? '' ),
			'label'       => sanitize_text_field( (string) ( $field['label'] ?? '' ) ),
			'placeholder' => sanitize_text_field( (string) ( $field['placeholder'] ?? '' ) ),
			'help'        => sanitize_text_field( (string) ( $field['help'] ?? '' ) ),
			'required'    => ! empty( $field['required'] ),
		];

		if ( in_array( $type, self::CHOICE_TYPES, true ) ) {
			$out['options'] = self::normalize_options( $field['options'] ?? [] );
		}

		if ( 'html' === $type ) {
			// Form copy: editors with unfiltered_html keep raw markup, others filtered.
			$content = (string) ( $field['content'] ?? '' );
			$out['content'] = current_user_can( 'unfiltered_html' ) ? $content : wp_kses_post( $content );
		}

		$out['config']      = self::normalize_config( $type, $field['config'] ?? [] );
		$out['conditional'] = self::normalize_conditional( $field['conditional'] ?? [] );

		return $out;
	}

	private static function normalize_options( $options ): array {
		if ( ! is_array( $options ) ) {
			return [];
		}
		$out = [];
		foreach ( array_slice( $options, 0, 200 ) as $opt ) {
			if ( ! is_array( $opt ) ) {
				continue;
			}
			$label = sanitize_text_field( (string) ( $opt['label'] ?? '' ) );
			$value = sanitize_text_field( (string) ( $opt['value'] ?? $label ) );
			if ( '' === $label && '' === $value ) {
				continue;
			}
			// Optional per-option price feeds the "priced options" pricing model.
			$price = isset( $opt['price'] ) && is_numeric( $opt['price'] ) ? round( (float) $opt['price'], 2 ) : 0.0;
			$out[] = [ 'label' => $label, 'value' => ( '' !== $value ? $value : $label ), 'price' => $price ];
		}
		return $out;
	}

	/** Per-type config (session-picker tabs/limits, number unit pricing). */
	private static function normalize_config( string $type, $config ): array {
		$config = is_array( $config ) ? $config : [];
		if ( 'number' === $type ) {
			// unit_price multiplies the entered number into the "priced options" total.
			$unit = isset( $config['unit_price'] ) && is_numeric( $config['unit_price'] ) ? round( (float) $config['unit_price'], 2 ) : 0.0;
			return [ 'unit_price' => $unit ];
		}
		if ( 'session_picker' === $type ) {
			$min = isset( $config['min'] ) ? max( 0, (int) $config['min'] ) : 4;
			$max = ( isset( $config['max'] ) && '' !== $config['max'] && null !== $config['max'] )
				? max( 0, (int) $config['max'] )
				: null;
			// Tabs the picker exposes; slot data itself lives in ofb_slots.
			$tabs = [];
			$raw_tabs = is_array( $config['tabs'] ?? null ) ? $config['tabs'] : [];
			foreach ( $raw_tabs as $tab ) {
				if ( ! is_array( $tab ) ) {
					continue;
				}
				$key = self::clean_id( $tab['key'] ?? '', '' );
				if ( '' === $key ) {
					continue;
				}
				$tabs[] = [ 'key' => $key, 'label' => sanitize_text_field( (string) ( $tab['label'] ?? $key ) ) ];
			}
			if ( empty( $tabs ) ) {
				$tabs = [
					[ 'key' => 'term', 'label' => __( 'School Term', 'open-form-builder' ) ],
					[ 'key' => 'holiday', 'label' => __( 'School Holiday', 'open-form-builder' ) ],
				];
			}
			return [ 'min' => $min, 'max' => $max, 'tabs' => $tabs ];
		}
		return [];
	}

	/** Conditional show/hide rule block. */
	public static function normalize_conditional( $cond ): array {
		$cond = is_array( $cond ) ? $cond : [];
		$action = ( ( $cond['action'] ?? 'show' ) === 'hide' ) ? 'hide' : 'show';
		$match  = ( ( $cond['match'] ?? 'all' ) === 'any' ) ? 'any' : 'all';
		$rules  = [];
		$raw_rules = is_array( $cond['rules'] ?? null ) ? $cond['rules'] : [];
		foreach ( array_slice( $raw_rules, 0, 50 ) as $rule ) {
			if ( ! is_array( $rule ) ) {
				continue;
			}
			$op = (string) ( $rule['op'] ?? 'is' );
			if ( ! in_array( $op, self::OPERATORS, true ) ) {
				$op = 'is';
			}
			$field = self::clean_name( $rule['field'] ?? '' );
			if ( '' === $field ) {
				continue;
			}
			$rules[] = [
				'field' => $field,
				'op'    => $op,
				'value' => sanitize_text_field( (string) ( $rule['value'] ?? '' ) ),
			];
		}
		return [
			'enabled' => ! empty( $cond['enabled'] ) && ! empty( $rules ),
			'action'  => $action,
			'match'   => $match,
			'rules'   => $rules,
		];
	}

	/** DOM/identifier-safe id. */
	public static function clean_id( $id, string $fallback ): string {
		$id = preg_replace( '/[^a-zA-Z0-9_\-]/', '', (string) $id );
		return ( is_string( $id ) && '' !== $id ) ? $id : $fallback;
	}

	/** Machine field name: lowercase, used in submission data and {tags}. */
	public static function clean_name( $name ): string {
		$name = sanitize_key( (string) $name );
		return $name;
	}

	/**
	 * Evaluate one field's conditional block against a map of submitted values.
	 * Mirrors the front-end JS evaluator so server and client agree on which
	 * fields are visible — visibility decides required-validation and email
	 * inclusion server-side.
	 *
	 * @param array $cond   Normalized conditional block.
	 * @param array $values name => submitted value (string or array).
	 * @return bool Whether the field should be visible.
	 */
	public static function is_visible( array $cond, array $values ): bool {
		if ( empty( $cond['enabled'] ) || empty( $cond['rules'] ) ) {
			return true;
		}
		$results = [];
		foreach ( $cond['rules'] as $rule ) {
			$results[] = self::rule_matches( $values[ $rule['field'] ] ?? '', $rule['op'], $rule['value'] );
		}
		$matched = ( 'any' === $cond['match'] ) ? in_array( true, $results, true ) : ! in_array( false, $results, true );
		// action=show: visible when matched. action=hide: hidden when matched.
		return ( 'hide' === $cond['action'] ) ? ! $matched : $matched;
	}

	private static function rule_matches( $value, string $op, string $test ): bool {
		$is_empty = is_array( $value ) ? ( 0 === count( array_filter( $value, fn( $v ) => '' !== (string) $v ) ) ) : ( '' === trim( (string) $value ) );

		switch ( $op ) {
			case 'empty':        return $is_empty;
			case 'not_empty':    return ! $is_empty;
			case 'is':           return self::value_contains( $value, $test, true );
			case 'is_not':       return ! self::value_contains( $value, $test, true );
			case 'contains':     return self::value_contains( $value, $test, false );
			case 'not_contains': return ! self::value_contains( $value, $test, false );
			case 'gt':           return is_numeric( self::scalar( $value ) ) && is_numeric( $test ) && (float) self::scalar( $value ) > (float) $test;
			case 'lt':           return is_numeric( self::scalar( $value ) ) && is_numeric( $test ) && (float) self::scalar( $value ) < (float) $test;
			case 'gte':          return is_numeric( self::scalar( $value ) ) && is_numeric( $test ) && (float) self::scalar( $value ) >= (float) $test;
			case 'lte':          return is_numeric( self::scalar( $value ) ) && is_numeric( $test ) && (float) self::scalar( $value ) <= (float) $test;
		}
		return false;
	}

	/** Exact (when $strict) or substring match against scalar or array values. */
	private static function value_contains( $value, string $test, bool $strict ): bool {
		$items = is_array( $value ) ? $value : [ $value ];
		foreach ( $items as $item ) {
			$item = (string) $item;
			if ( $strict ? ( $item === $test ) : ( '' !== $test && false !== strpos( $item, $test ) ) ) {
				return true;
			}
		}
		return false;
	}

	private static function scalar( $value ): string {
		return is_array( $value ) ? (string) reset( $value ) : (string) $value;
	}

	/**
	 * Flatten all fields across steps into a single list keyed by field name.
	 * Used by submission handling, tag replacement and conditional evaluation.
	 *
	 * @return array<string,array> name => field
	 */
	public static function fields_by_name( array $schema ): array {
		$out = [];
		foreach ( ( $schema['steps'] ?? [] ) as $step ) {
			foreach ( ( $step['fields'] ?? [] ) as $field ) {
				if ( '' !== ( $field['name'] ?? '' ) ) {
					$out[ $field['name'] ] = $field;
				}
			}
		}
		return $out;
	}
}
